### ISSUE TITLE
Silva taxonomic data formatted for DADA2 

### ISSUE THREAD

**Issue by monaparizadeh** [BikLab/nematode-rRNA-variants#1]
Hi Holly!

I'd like to assign taxonomy of nematode ASVs using DADA2, and so I'm working on making a DADA2-formatted file from the Silva 132 nematode database. I was wondering if you have any experience in this case that you can share. I appreciate it!

Best,
Mona

**Comment by tiagojp** [comment]
Dear Mona,

You'll need to convert the silva files into qzas (i.e. qiime format files). To download the qiime_132 release check this link: https://www.arb-silva.de/download/archive/qiime/.

You will have one file for the reference fasta (i.e. DNA sequences in a fasta format) and one file for the taxonomy (i.e. taxonomy string/ranks of associated sequences).

To convert the files into qiime format, use the following commands:

qiime tools import   --input-path majority_taxonomy_all_levels.txt   --output-path majority_taxonomy_all_levels   --type 'FeatureData[Taxonomy]' --source-format HeaderlessTSVTaxonomyFormat

qiime tools import   --input-path silva132_99.fna   --output-path silva132_99   --type 'FeatureData[Sequence]’ (99 here indicates that sequences were clustered at 99% similarity).

Best of luck!

Tiago
--------
Tiago José Pereira, PhD
Department of Nematology
Bik Lab: 2126 Genomics Building
University of California, Riverside
900 University Avenue, Riverside, CA 92521, USA
https://biklab.github.io/team/

On Jun 26, 2019, at 12:34 PM, Mona Parizadeh <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Holly!

I'd like to assign taxonomy of nematode ASVs using DADA2, and so I'm working on making a DADA2-formatted file from the Silva 132 nematode database. I was wondering if you have any experience in this case that you can share. I appreciate it!

Best,
Mona

**Comment by monaparizadeh** [comment]
Thanks a lot Tiago for your quick response and all the details! I'm actually looking for a database reformatted to be used directly in the DADA2 pipeline (which I'm working on now). Otherwise, I can switch to Qiime and try your way!

Best,
M

**Comment by hollybik** [comment]
Hi Mona, we currently do all our taxonomy assignments in QIIME2 (and actually we've been using BLAST+ for these assignments), so we are just using either the SILVA database directly downloaded, or the QIIME-formatted version of SILVA (which just modifies the taxonomy strings and makes 99% OTUs to collapse close relatives). But I'm curious - what kind of formatting does DADA2 need if you want to use the SILVA database directly within that program? We may do so in the future, so please post and example of files/strings needed for DADA2

**Comment by monaparizadeh** [comment]
Hi Holy and thanks for your response! The id lines of the database formatted for DADA2 should follow: 

>Level1;Level2;Level3;Level4;Level5;Level6;

https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

**Comment by monaparizadeh** [comment]
There is a ">" before "Level1" that github converts it to the gray line! But you'll see the good formatting in the above link.

**Comment by hollybik** [comment]
Thanks for the link! So you could just write a script to replace the accession number in the SILVA database (the FASTA file of ref seqs) with the full taxonomy string delimited by semicolons (basically the info from the second column of the QIIME taxonomy mapping file). We don't have a script to do that yet, but it should be a fairly simple Python or shell script to write. Good luck if you decide to go down that route!
